#!/usr/bin/dh-exec

etc/init/corosync.conf
etc/logrotate.d/corosync
lib/systemd/system/corosync.service [linux-any]
usr/bin/corosync-blackbox
usr/bin/corosync-xmlproc
usr/sbin/corosync
usr/sbin/corosync-cfgtool
usr/sbin/corosync-keygen
usr/sbin/corosync-cpgtool
usr/sbin/corosync-quorumtool
usr/sbin/corosync-cmapctl
usr/share/man/man5/corosync*.5
usr/share/man/man5/votequorum.5
usr/share/man/man8/corosync-blackbox.8
usr/share/man/man8/corosync-cfgtool.8
usr/share/man/man8/corosync-cmapctl.8
usr/share/man/man8/corosync-cpgtool.8
usr/share/man/man8/corosync-keygen.8
usr/share/man/man8/corosync-quorumtool.8
usr/share/man/man8/corosync-xmlproc.8
usr/share/man/man8/corosync.8
usr/share/man/man8/corosync_overview.8
usr/share/man/man8/cmap_keys.8
usr/share/doc/corosync/README.recovery
usr/share/doc/corosync/SECURITY
usr/share/doc/corosync/AUTHORS
usr/share/doc/corosync/INSTALL
usr/share/augeas/lenses/corosync.aug
usr/share/augeas/lenses/tests/test_corosync.aug
etc/corosync/corosync.*example* usr/share/doc/corosync/examples
etc/corosync/uidgid.d
debian/corosync.conf etc/corosync
usr/share/corosync/xml2conf.xsl
var/lib/corosync
